source "https://rubygems.org"

gem 'rake', '~> 0.9.2'
gem 'rubypython', '=0.5.3'
gem 'rack', '~> 1.4.1'
gem 'jekyll', '~> 0.11.2'
gem 'rdiscount', '~> 1.6.8'
gem 'pygments.rb', '~> 0.2.12'
gem 'RedCloth', '~> 4.2.9'
gem 'haml', '~> 3.1.6'
gem 'compass', '~> 0.12.1'
gem 'rubypants', '~> 0.2.0'
gem 'stringex', '~> 1.4.0'
gem 'liquid', '~> 2.3.0'
gem 'kramdown', '~> 0.13.7'
gem 'sinatra', '~> 1.3.2'
  
group :development do
  gem 'rb-fsevent'
  gem 'heroku'
  gem 'rake', '~> 10.0'
  gem 'jekyll', '~> 2.0'
  gem 'jekyll-page-hooks', '~> 1.2'
  gem 'jekyll-date-format', '~> 1.0'
  gem 'jekyll-sitemap'
  gem 'rdiscount', '~> 2.0'
  gem 'RedCloth', '~> 4.2.9'
  gem 'haml', '~> 4.0'
  gem 'compass', '~> 0.12.2'
  gem 'sass-globbing', '~> 1.0.0'
  gem 'rubypants', '~> 0.2.0'
  gem 'rb-fsevent', '~> 0.9'
  gem 'stringex', '~> 1.4.0'
end

gem 'sinatra', '~> 1.4.2'
